---
ModelName : MAR_RESNET34_CROPPED_256_new_train

PathSave : outputs

CheckpointName : checkpoint.pt

Train : 
  - new/train0.csv
Test :
  - new/test0.csv
  - new/test1.csv
  - new/test2.csv

CheckpointFreq : 5

NEpochs : 100

BatchSize : 32

Seed : 0

Model :
  Layers :
    - 3
    - 4
    - 6
    - 3
  OutClasses : 5
  Channels : 1

TransformTrain:
  ToRGB :
    num_output_channels : 3
  ColorJitter:
    brightness : 0.5
  ToGrayscale :
    num_output_channels : 1
  VerticalFlip: 
    p : 0.5
  HorizontalFlip : 
    p : 0.5
  Rotation : 
    min : -90
    max : 90
  CenterCrop :
    size : 128
  Resize :
    width : 256
    height : 256

TransformTest:
  CenterCrop :
    size : 128
  Resize :
    width : 256
    height : 256
 
Optimizer : 
  lr : 0.001
  weight_decay : 0.000001

Scheduler :
  gamma : 0.95
